name: frame_vosk_mlkit_nonlatin
description: "Connects to Frame and streams audio from the phone's microphone, which is sent through a local (on Host device) vosk speech-to-text engine, translates the text into a target language on-device using ML Kit, and displays the translated text on the Frame display using TextSpriteBlock."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vosk_flutter: ^0.3.48
  record: ^5.0.5
  buffered_list_stream: ^1.3.0
  google_mlkit_translation: ^0.11.0
  logging: ^1.2.0
  simple_frame_app: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/code.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/sprite.min.lua
    - packages/simple_frame_app/lua/text_sprite_block.min.lua
    - assets/vosk-model-small-en-us-0.15.zip
    - assets/frame_app.min.lua
